### ISSUE TITLE
ImportError: No module named httplib

### ISSUE THREAD

**Issue by acs-ferreira** [ReinerNippes/nextcloud#39]
`./prepare_system.sh` on fresh Ubuntu 18.04.2
```
++ uname -m
+ '[' x86_64 == aarch64 ']'
+ PYTHON_BIN=/usr/bin/python
+ install_pip
+ curl https://bootstrap.pypa.io/get-pip.py
+ /usr/bin/python
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1669k  100 1669k    0     0  10.3M      0 --:--:-- --:--:-- --:--:-- 10.4M
Traceback (most recent call last):
  File "<stdin>", line 21492, in <module>
  File "<stdin>", line 197, in main
  File "<stdin>", line 82, in bootstrap
  File "/tmp/tmpVUCRup/pip.zip/pip/_internal/__init__.py", line 19, in <module>
  File "/tmp/tmpVUCRup/pip.zip/pip/_vendor/urllib3/__init__.py", line 8, in <module>
  File "/tmp/tmpVUCRup/pip.zip/pip/_vendor/urllib3/connectionpool.py", line 11, in <module>
  File "/tmp/tmpVUCRup/pip.zip/pip/_vendor/urllib3/exceptions.py", line 2, in <module>
  File "/tmp/tmpVUCRup/pip.zip/pip/_vendor/urllib3/packages/six.py", line 203, in load_module
  File "/tmp/tmpVUCRup/pip.zip/pip/_vendor/urllib3/packages/six.py", line 115, in _resolve
  File "/tmp/tmpVUCRup/pip.zip/pip/_vendor/urllib3/packages/six.py", line 82, in _import_module
ImportError: No module named httplib
```

**Comment by ReinerNippes** [comment]
should be fixed here: https://github.com/ReinerNippes/nextcloud/compare/python3
